sudo: required
services:
    - docker

script:
    - docker build -t fred/node2 .
    - docker images fred/node2

before_deploy:
    - echo "$DOCKER_PASSWORD" | docker login -u test --password-stdin

deploy:
    provider: script
    script: docker push $DOCKER_USERNAME/node2test
    on:
        branch: main
    