sudo: required
services:
    - docker

script:
    - docker build -t fred/node2 .
    - docker images fred/node2

before_deploy:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

deploy:
    provider: script
    script: docker push fmotot/node2test
    on:
        branch: main
    