sudo: required
services:
    - docker

script:
    - docker build -t fmotot/node2test .
    - docker images fmotot/node2test

deploy:
    provider: script
    script: bash docker_push
    on:
        branch: main
    